# Generated by Django 5.2.8 on 2025-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_image_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/user_img.png', null=True, upload_to='profile_images/'),
        ),
    ]
