# Generated by Django 5.2.8 on 2025-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newchat',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newchat',
            name='role',
        ),
        migrations.AddField(
            model_name='newchat',
            name='ai_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newchat',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
