# Generated by Django 5.2.8 on 2025-12-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0002_remove_newchat_content_remove_newchat_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchat',
            name='ai_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='user_message',
            field=models.TextField(),
        ),
    ]
