# Generated by Django 5.2.8 on 2025-12-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0003_alter_newchat_ai_message_alter_newchat_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchat',
            name='ai_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
