# Generated by Django 5.2.8 on 2025-12-26 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0004_alter_newchat_ai_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='newchat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/audio/'),
        ),
        migrations.AddField(
            model_name='newchat',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('audio', 'Audio')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='newchat',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='chat_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
