# Generated by Django 5.2.8 on 2025-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0005_newchat_audio_file_newchat_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newchat',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='newchat',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='newchat',
            name='uploaded_file',
        ),
        migrations.AlterField(
            model_name='newchat',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newchat',
            name='user_message',
            field=models.TextField(),
        ),
    ]
