# Generated by Django 5.2.8 on 2025-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0006_remove_newchat_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newchat',
            name='ai_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/ai/'),
        ),
        migrations.AddField(
            model_name='newchat',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/user/'),
        ),
    ]
