# Generated by Django 5.2.8 on 2025-12-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0007_newchat_ai_file_newchat_user_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newchat',
            name='ai_file',
        ),
        migrations.RemoveField(
            model_name='newchat',
            name='user_file',
        ),
    ]
